import { defineConfig, type Plugin } from "vite"
import { viteSingleFile } from "vite-plugin-singlefile"
import tailwindcss from "@tailwindcss/vite"
import { writeFileSync } from "fs"
import { resolve } from "path"

// After the single inlined index.html is emitted, base64-encode it and write a
// generated TS module that the PKJS bundle (src/ts/index.ts) imports and opens
// as a `data:text/html;base64,...` URI from the showConfiguration handler. This
// keeps the settings page fully self-contained / offline (Clay-style).
function embedAsBase64(): Plugin {
  return {
    name: "embed-config-as-base64",
    writeBundle(_options, bundle) {
      const html = Object.values(bundle).find(
        (chunk) => chunk.type === "asset" && chunk.fileName.endsWith(".html"),
      )
      if (!html || html.type !== "asset") {
        throw new Error("embed-config-as-base64: no index.html asset found in bundle")
      }
      const source =
        typeof html.source === "string" ? html.source : Buffer.from(html.source)
      const base64 = Buffer.from(source).toString("base64")
      const out = resolve(__dirname, "page.generated.ts")
      writeFileSync(
        out,
        `// AUTO-GENERATED by vite.config.ts — do not edit\n` +
          `export const CONFIG_PAGE = ${JSON.stringify(base64)}\n`,
      )
    },
  }
}

export default defineConfig({
  root: __dirname,
  esbuild: { jsx: "automatic", jsxImportSource: "preact" },
  // @szhsin/react-autocomplete imports from "react"; alias it onto Preact's compat
  // layer so it runs under Preact. (Icons use raw @phosphor-icons/core SVGs, no React.)
  resolve: {
    alias: {
      react: "preact/compat",
      "react-dom": "preact/compat",
      "react-dom/client": "preact/compat",
      "react/jsx-runtime": "preact/jsx-runtime",
    },
  },
  plugins: [tailwindcss(), viteSingleFile(), embedAsBase64()],
  build: {
    outDir: resolve(__dirname, ".vite-dist"),
    emptyOutDir: true,
  },
})
